# -*- coding: utf-8 -*-
"""Fibonaccigenerator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1amNLN-pw--vjtZo7c1DBgCF5nYKp_svo
"""

def generate_fibonacci(n):
    fibonacci_sequence = [0, 1]

    for i in range(2, n):
        next_number = fibonacci_sequence[-1] + fibonacci_sequence[-2]
        fibonacci_sequence.append(next_number)

    return fibonacci_sequence

# Example: Generate the first 10 Fibonacci numbers
n = 10
fibonacci_numbers = generate_fibonacci(n)
print(f"Fibonacci sequence up to {n} numbers: {fibonacci_numbers}")

